# Generated by Django 4.2.3 on 2023-08-14 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('catname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.ImageField(upload_to='product_img')),
                ('product_name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('expirydate', models.DateField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_cosmeticapp.categories')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_cosmeticapp.brands')),
            ],
        ),
    ]
